"""initial schema

Revision ID: d70a10ed7d0c
Revises: 
Create Date: 2025-12-18 07:11:28.879810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd70a10ed7d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_code', sa.Text(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('min_duration_ticks', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_tick', sa.Integer(), nullable=True),
    sa.Column('end_tick', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propagation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_signal', sa.Text(), nullable=False),
    sa.Column('target_signal', sa.Text(), nullable=False),
    sa.Column('lag_ticks', sa.Integer(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_dependencies',
    sa.Column('source_signal', sa.Text(), nullable=False),
    sa.Column('target_signal', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_signal', 'target_signal')
    )
    op.create_table('signals',
    sa.Column('signal_code', sa.Text(), nullable=False),
    sa.Column('component_code', sa.Text(), nullable=False),
    sa.Column('column_name', sa.Text(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('polarity', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible_to_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('signal_code')
    )
    op.create_table('timeseries_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('component_code', sa.Text(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeseries_points_component_code'), 'timeseries_points', ['component_code'], unique=False)
    op.create_index(op.f('ix_timeseries_points_tick'), 'timeseries_points', ['tick'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('component_code', sa.Text(), nullable=True),
    sa.Column('signal_code', sa.Text(), nullable=True),
    sa.Column('tick_start', sa.Integer(), nullable=True),
    sa.Column('tick_end', sa.Integer(), nullable=True),
    sa.Column('peak_value', sa.Float(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('alert_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'alert_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_alerts')
    op.drop_table('user_roles')
    op.drop_table('alert_events')
    op.drop_table('users')
    op.drop_index(op.f('ix_timeseries_points_tick'), table_name='timeseries_points')
    op.drop_index(op.f('ix_timeseries_points_component_code'), table_name='timeseries_points')
    op.drop_table('timeseries_points')
    op.drop_table('signals')
    op.drop_table('signal_dependencies')
    op.drop_table('roles')
    op.drop_table('propagation_evidence')
    op.drop_table('incidents')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
